### PR TITLE
ARSN-378: adding missing authorizations to actionMapBP

### PR DESCRIPTION
**Pull request by benzekrimaha**
This pull request modifies the `actionMapBP` object in `lib/policyEvaluator/utils/actionMaps.ts` to include additional properties, extending its functionality.

Main change:

* <a href="diffhunk://#diff-7fb88a375e077c195e7a6345016d77a135949a6da340c76c6b57c0e3d05cccc9L80-R85">`lib/policyEvaluator/utils/actionMaps.ts`</a>: Modified the `actionMapBP` object to include additional properties, such as `bucketDeleteCors`, `bucketDeleteLifecycle`, and `bucketDeleteReplication`.

### CODE REVIEW

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
@bert-e reset

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
@bert-e create_pull_requests

**Review by anurag4DSB — APPROVED** [review]

**Review by KazToozs — APPROVED** [review]

**Comment by benzekrimaha** [comment]
@bert-e approve

**Pull request merged**
