### PR TITLE
FT: Add putBucketReplication

### PR DESCRIPTION
**Pull request by bennettbuchanan**

### CODE REVIEW

**Comment by rahulreddy** [comment]
@bennettbuchanan You should be adding `s3:PutReplicationConfiguration` to `lib/policyEvaluator/RequestContext.js` for policy checks.

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
e2e passed here http://ci.ironmann.io/gh/scality/Integration/13197

**Pull request merged**
