### PR TITLE
[ARSN-335] ✨ Implement GHAS

### PR DESCRIPTION
**Pull request by gaspardmoindrot**

### CODE REVIEW

**Review by tcarmet — CHANGES_REQUESTED** [review]
retarget and rebase your changes on the dev/7.4 branch.

**Review by tcarmet — CHANGES_REQUESTED** [review]
Review your commit to remove unwanted mention of authors.

**Review by tcarmet — APPROVED** [review]

**Comment by gaspardmoindrot** [comment]
`ping`

**Review by tmacro — APPROVED** [review]

**Pull request merged**
