### PR TITLE
bugfix: ZENKO 2702 Use replica set config instead of rs0

### PR DESCRIPTION
**Pull request by miniscruff**
We already had the replica set value in the config and was loading it but was using a fixed `rs0` in place of the real value.

### CODE REVIEW

**Review by alexanderchan-scality — APPROVED** [review]

**Review by nicolas2bert — APPROVED** [review]

**Review by anurag4DSB — CHANGES_REQUESTED** [review]
Shouldn't we create development/8.2 in Arsenal?

We are planning to concentrate on only Zenko v2.x
In the future if we have a bug in Zenko v1.x and we have to update arsenal in cloud server, this might break things.

I checked the ticket and it's fix version is only 2.x so I am guessing there is nothing planned for cloudsevrer dev/8.1.

**Review by anurag4DSB — APPROVED** [review]

**Comment by anurag4DSB** [comment]
Okay approved, after checking cloud server config and your PR summary :D. 
But I think we should still make a development/8.2 for 2.x
what do you think?
CC @jonathan-gramain

**Comment by miniscruff** [comment]
> Shouldn't we create development/8.2 in Arsenal?
> 
> We are planning to concentrate on only Zenko v2.x
> In the future if we have a bug in Zenko v1.x and we have to update arsenal in cloud server, this might break things.
> 
> I checked the ticket and it's fix version is only 2.x so I am guessing there is nothing planned for cloudsevrer dev/8.1.

The versioning of our packages are a mystery to me, I picked 8.1 as it was the default and @rahulreddy said that was fine over slack.

**Comment by anurag4DSB** [comment]
> > Shouldn't we create development/8.2 in Arsenal?
> 
> > 
> 
> > We are planning to concentrate on only Zenko v2.x
> 
> > In the future if we have a bug in Zenko v1.x and we have to update arsenal in cloud server, this might break things.
> 
> > 
> 
> > I checked the ticket and it's fix version is only 2.x so I am guessing there is nothing planned for cloudsevrer dev/8.1.
> 
> 
> 
> The versioning of our packages are a mystery to me, I picked 8.1 as it was the default and @rahulreddy said that was fine over slack.

This PR is good for 8.1. We do not have any breaking changes till now. I was considering the features we will add in the future specific to 2.x.

**Review by ilkescality — APPROVED** [review]

**Comment by rahulreddy** [comment]
If you ask me I would prefer 9.0 but I don't want to break RING 9 convention. Since 8.1 didn't have any breaking changes, we kept it as-is. Let me ask the question in the channel and see what everyone thinks.

**Review by rahulreddy — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Comment by miniscruff** [comment]
@bert-e status

**Comment by miniscruff** [comment]
@bert-e approve

**Comment by miniscruff** [comment]
@bert-e help

**Pull request merged**
