### PR TITLE
Feature/arsn 33/add common lifecycle rule helpers

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
Move lifecycle rule methods to arsenal to be reused in cloudserver for `x-amz` header generation

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
ping

**Review by miniscruff — APPROVED** [review]
Since it is a move more then new code I am approving out of "historical reasons". Any improvements or adjustments would feel weird to make now.

**Review by naren-rajendran — APPROVED** [review]

**Review by saitharunthodupunuru — APPROVED** [review]

**Pull request merged**
