### PR TITLE
ft: ZENKO-1282 add scheduled resume for ingestion

### PR DESCRIPTION
**Pull request by philipyoo**
Extend backbeat api routes scheduled resume to support ingestion service

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@bert-e wait

**Review by bennettbuchanan — APPROVED** [review]

**Comment by philipyoo** [comment]
@bert-e help

**Review by jonathan-gramain — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
@philipyoo Can you change the package.json version, you can increment patch version for this i.e 8.1.x where `x` is the patch version.

**Comment by philipyoo** [comment]
@bert-e approve

**Pull request merged**
