### PR TITLE
S3C-586: [policies] Allow sso scope checking

### PR DESCRIPTION
**Pull request by alexandre-merle**
Allow vault sso to run policy evaluator

See https://scality.atlassian.net/browse/S3C-586

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
At ALexandre's request, and since the maintainer already approved, let's merge without the dropme:
@ironman-machine r=ef91d7f

**Comment by alexandre-merle** [comment]
closing reopened for clean ultron

**Comment by DavidPineauScality** [comment]
again...
@ironman-machine r- r=ef91d7f

**Comment by DavidPineauScality** [comment]
@ironman-machine r- r+

**Comment by alexandre-merle** [comment]
@ironman-machine try

**Comment by DavidPineauScality** [comment]
@ironman-machine r-

**Comment by alexandre-merle** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
Merging manually.

**Comment by alexandre-merle** [comment]
@rahulreddy thanks :)

**Pull request merged**
