### PR TITLE
bf: abortmpu days parsing

### PR DESCRIPTION
**Pull request by dora-korpar**
Fix for parsing of `AbortIncompleteMultipartUpload` lifecycle action

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
btw, can you update the target to rel/7.4?

**Comment by bennettbuchanan** [comment]
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
@ironman-machine r- r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Pull request closed without merging**
