### PR TITLE
FIX: Trim white space for v4 auth

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
Fixes S3C-143

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
@ironman-machine check it

**Comment by GiorgioRegni** [comment]
ouch, this one was sneaky

**Comment by LaurenSpiegel** [comment]
@ironman-machine go

**Comment by LaurenSpiegel** [comment]
@GiorgioRegni, that's a feature here 😄  Plus, that's what the node sdk does.

**Pull request merged**
