### PR TITLE
bugfix: S3C-1985 fix crash in vault-md on listing

### PR DESCRIPTION
**Pull request by jonathan-gramain**
Add a check on 'value' being defined in trimMetadata().

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Review by ploki — APPROVED** [review]
if the function is supposed to do nothing beside of returning undefined when value is undefined, LGTM

**Review by bennettbuchanan — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by Stephane-Scality** [comment]
Please do not fix this issue in the same jira ticket as the initial ticket otherwise it makes no sense for version tracking.

**Comment by Stephane-Scality** [comment]
@bert-e wait

**Comment by jonathan-gramain** [comment]
Closing due to an issue with the fix + new ticket, replaced by: https://github.com/scality/Arsenal/pull/708

**Pull request closed without merging**
