### PR TITLE
feat(typescript): add clustering definition

### PR DESCRIPTION
**Pull request by michael-zapata**
Only implementing what we need right now.

Based on #141

### CODE REVIEW

**Comment by ThibaultRiviere** [comment]
:+1:

**Comment by mvaude** [comment]
:+1:

**Comment by lamphamsy** [comment]
👍

**Comment by rahulreddy** [comment]
Is this merge-able or is it dependent on any other PR?

**Comment by michael-zapata** [comment]
You can merge it, it doesn't depend on anything.

**Comment by michael-zapata** [comment]
Is there any plan to consider a merge here @rahulreddy?

**Comment by rahulreddy** [comment]
Looks like I missed the update due to the mayhem last week. Merging this.

**Pull request merged**
