### PR TITLE
Revert "bf: ARSN-340 bump socket.io dep to 4.6.1"

### PR DESCRIPTION
**Pull request by nicolas2bert**
This reverts commit af3fd17ec2eef9a061e088b4e6857946148d4801.

Issue: ARSN-347

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e help

**Comment by nicolas2bert** [comment]
Except for the "dependency-review-action," all actions are successful. The reason for its failure is the rollback of the socket.io version update. To overcome this, I will employ the "bert-e bypass_build_status" command.

**Comment by francoisferrand** [comment]
* why do we need to rollback? This will bring back lots of CVEs...
* is this rollback only on `7.10`, or will it affect `8.1` as well ?

**Comment by nicolas2bert** [comment]
We encountered a setback in the CloudServer 7.x and 8.x when we updated socket.io and its client. A file backend test failed, and despite my efforts, I couldn't fix it promptly. Consequently, I made the decision to revert the changes made to the socket.io update, allowing development in CloudServer to proceed smoothly again.

**Comment by nicolas2bert** [comment]
@bert-e bypass_build_status

**Pull request closed without merging**
