### PR TITLE
ARSN-200: fix probe server readiness path

### PR DESCRIPTION
**Pull request by alexanderchan-scality**

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]
not that it matters much but using /live for both was my intention as we had only used one form of readiness at the time so I just implemented the one handler.

**Review by naren-rajendran — APPROVED** [review]

**Comment by alexanderchan-scality** [comment]
@miniscruff I see. I had made this change as it was not backwards compatible with previous versions of backbeat images. I had probably missed the intention for the change since it was made as part of the typescript refactor.

**Comment by miniscruff** [comment]
> @miniscruff I see. I had made this change as it was not backward compatible with previous versions of backbeat images. I had probably missed the intention for the change since it was made as part of the typescript refactor.

We should definitely do this change, just making a point as to why it was the way it was. It looks like a typo bug but was more of a shortcut. Just have to check backbeat uses to make sure the two routes are used properly.

**Comment by alexanderchan-scality** [comment]
ping

**Pull request merged**
