### PR TITLE
backport: S3C-1622 statsmodel changes

### PR DESCRIPTION
**Pull request by philipyoo**
Opening for review. Please do not merge. Goes with https://github.com/scality/backbeat/pull/500

For this backport, I decided to keep backbeat Metrics methods and api routes file in this repo and only keep StatsModel changes in arsenal.

Note: Some commits were partial backports.
      Backbeat metrics/routes were kept in backbeat.
backport the following commits from development/8.1:

- 8fd50cd rf: S3C-1399 Add Backbeat metrics and routes
- 114cbf5 bf: use expired interval to avg out throughput
- f904f04 fix: do not crash on empty backbeat stats
- 9e234e2 bf: zero-fill response for getAllStats
- bf95506 ft: ZENKO-925 increase crr metrics expiry to 24hrs
- 125ccbb bugfix: ZENKO-1024 Add pending counters

### CODE REVIEW

**Comment by philipyoo** [comment]
@bert-e wait

**Comment by jonathan-gramain** [comment]
> For this backport, I decided to keep backbeat Metrics methods and api routes file in this repo and only keep StatsModel changes in arsenal.

What is the rationale? There can be a valid reason for it, if not, it seems best to try to match the state of the code in 8.0 to reduce the number of merge conflicts in the future.

**Comment by philipyoo** [comment]
@jonathan-gramain Hmm, ya maybe best to match. It was mainly personal preference honestly. I'd like to eventually move back the metrics routes to backbeat since cloudserver no longer needs these methods.

**Comment by jonathan-gramain** [comment]
@philipyoo understood, then once the actual backport is made, moving the routes to backbeat can be made as a second step that can be a regular PR targeted at 7.4 and above at once, correct?

**Pull request closed without merging**
