### PR TITLE
[Tests](fix): Fix flaky test timeout

### PR DESCRIPTION
**Pull request by alexandre-merle**
- Increase timeout to remove flacky test from
  public Circle CI

Fixes https://github.com/scality/Arsenal/issues/93

### CODE REVIEW

**Comment by rahulreddy** [comment]
👍

**Comment by rahulreddy** [comment]
Can you fix the commit message typo, from `flacky` to `flaky` 😄

**Comment by rahulreddy** [comment]
I just realized, this should probably go into rel/1.1 since it's not related to just Smart Bulb release

**Comment by alexandre-merle** [comment]
Done :)

**Comment by alexandre-merle** [comment]
you right :) i will do that too

**Comment by DavidPineauScality** [comment]
:+1: :) Failed too many times for nothing :D

**Comment by DavidPineauScality** [comment]
Note: This one should be closed in favor of #113

**Comment by alexandre-merle** [comment]
@DavidPineauScality this one is for master :)

**Comment by DavidPineauScality** [comment]
Yes, and that's what forward ports are for. To port fixes pushed into release branches into the associated master branches.

**Comment by alexandre-merle** [comment]
Closing for https://github.com/scality/Arsenal/pull/114 :)

**Pull request closed without merging**
