### PR TITLE
FWD: 7.4 Setting up EVE pipeline

### PR DESCRIPTION
**Pull request by tcarmet**
* setup EVE Pipeline

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
@ironman-machine
r-
after=Federation#1343
r+

**Comment by tcarmet** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by tcarmet** [comment]
I can't see the builds logs, Is it flaky? or is there something we can fix ?

**Comment by DavidPineauScality** [comment]
Nope, there's an issue we need to fix in Federation, and I made a mistake in my ultron command T.T
@ironman-machine 
r-
after=scality/Federation#1343
r+

**Comment by DavidPineauScality** [comment]
@ironman-machine r- r+

**Pull request merged**
