### PR TITLE
ARSN-224: fix missing default for models imports

### PR DESCRIPTION
**Pull request by ghost**
Fixes this in cloudserver:

```json
{"name":"S3","time":1654855148883,"error":"BackendInfo is not a constructor","stack":"TypeError: BackendInfo is not a constructor\n    at DataWrapper.uploadPartCopy (/usr/src/app/node_modules/arsenal/build/lib/storage/data/DataWrapper.js:376:29)\n    at goGetData (/usr/src/app/lib/api/objectPutCopyPart.js:254:18)\n    at nextTask (/usr/src/app/node_modules/async/dist/async.js:5297:14)\n    at next (/usr/src/app/node_modules/async/dist/async.js:5304:9)\n    at /usr/src/app/node_modules/async/dist/async.js:906:16\n    at /usr/src/app/lib/api/objectPutCopyPart.js:240:32\n    at /usr/src/app/node_modules/arsenal/build/lib/storage/metadata/MetadataWrapper.js:211:20\n    at /usr/src/app/node_modules/arsenal/node_modules/async/dist/async.js:473:16\n    at next (/usr/src/app/node_modules/arsenal/node_modules/async/dist/async.js:5332:29)\n    at /usr/src/app/node_modules/arsenal/node_modules/async/dist/async.js:972:16","level":"fatal","message":"caught error","hostname":"kw013-prod-cloudserver-backend-0-17615-4028","pid":74}
```

Also make sure the result returned by Arsenal for the Bucket Notification Configuration is consistent with what is expected in Cloudserver tests and what was returned before.

### CODE REVIEW

**Review by jbertran — DISMISSED** [review]
Seems there are a few more missing, not related to your specific issue but they'll crash as well eventually:

```
❯ git grep 'require.*models.*' lib/storage lib/algos
lib/storage/data/DataWrapper.js:11:const BackendInfo = require('../../models/BackendInfo');
lib/storage/metadata/MetadataWrapper.js:3:const BucketInfo = require('../../models/BucketInfo');
lib/storage/metadata/bucketclient/BucketClientInterface.js:3:const BucketInfo = require('../../../models/BucketInfo');
lib/storage/metadata/file/BucketFileInterface.js:5:const BucketInfo = require('../../../models/BucketInfo');
lib/storage/metadata/mongoclient/MongoClientInterface.js:18:const BucketInfo = require('../../../models/BucketInfo');
lib/storage/metadata/proxy/BucketdRoutes.js:4:const BucketInfo = require('../../../models/BucketInfo');
```
Reason: we're not migrating `storage` and `algos` because they're about to be moved to Armory.

**Comment by ghost** [comment]
Hi @jbertran , are you up to date? Picking randomly a line from your comment, we already have the default import: https://github.com/scality/Arsenal/blob/d407cd702b18b254fcc0c3d77882544d709f0981/lib/storage/metadata/MetadataWrapper.js#L3

Getting this using your command:
```
lib/storage/data/DataWrapper.js:const BackendInfo = require('../../models/BackendInfo').default;
lib/storage/metadata/MetadataWrapper.js:const BucketInfo = require('../../models/BucketInfo').default;
lib/storage/metadata/bucketclient/BucketClientInterface.js:const BucketInfo = require('../../../models/BucketInfo').default;
lib/storage/metadata/file/BucketFileInterface.js:const BucketInfo = require('../../../models/BucketInfo').default;
lib/storage/metadata/mongoclient/MongoClientInterface.js:const BucketInfo = require('../../../models/BucketInfo').default;
lib/storage/metadata/proxy/BucketdRoutes.js:const BucketInfo = require('../../../models/BucketInfo').default;
```

**Review by KillianG — APPROVED** [review]

**Review by XinLi0207 — APPROVED** [review]

**Comment by ghost** [comment]
I am approving this, I got a green build in Cloudserver https://eve.devsca.com/github/scality/cloudserver/#/builders/3/builds/17628

Please let me know or open a ticket if you see more required changes.

**Pull request merged**
