### PR TITLE
ARSN-306 delimiter versions null key support

### PR DESCRIPTION
**Pull request by jonathan-gramain**
- The first commit refactors DelimiterVersions algorithm into a cleaner state machine
- The second commit adds the support proper for null keys

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
ping

**Comment by watsaqat** [comment]
We should considering adding https://github.com/typescript-eslint to Arsenal. There's a few rules in particular that I'd recommend enabling and combing through this PR with: no-inferrable-types and no-untyped-public-signature, though there are likely other useful ones.

**Review by tmacro — APPROVED** [review]

**Review by watsaqat — APPROVED** [review]

**Pull request merged**
