### PR TITLE
fix(arsenal): remove circular dependency

### PR DESCRIPTION
**Pull request by michael-zapata**
This was creating odd behaviours when importing these functionalities and the errors themselves.

### CODE REVIEW

**Comment by MathieuCassagne** [comment]
:+1:

**Comment by LaurenSpiegel** [comment]
👍

**Comment by rahulreddy** [comment]
Can you create an issue for the bug and reference the issue in the commit?
I will merge after that.

**Comment by michael-zapata** [comment]
Done.

**Comment by rahulreddy** [comment]
Thanks, merging this.

**Pull request merged**
