### PR TITLE
BF: Restrict policy top level properties

### LINKED ISSUE #121: top level keys in policies are not whitelisted
Policy validator should return false for this policy
```json
{
	"Version": "2012-10-17",
	"Statement": [{
		"Effect": "Allow",
		"Action": ["s3:ListAllMyBuckets", "s3:PutBucket"],
		"Resource": "arn:aws:s3:::*"
	}],
    "Condition": {"DateGreaterThan": { "aws:CurrentTime": "2013-06-30T00:00:00Z"}}
}
```
In the above policy, Condition is not a valid key.

### PR DESCRIPTION
**Pull request by rahulreddy**
Fix #121

### CODE REVIEW

**Comment by alexandre-merle** [comment]
Can you add just an unit test to ensure we don't go into this bug again :)

**Comment by rahulreddy** [comment]
Added test.

**Comment by alexandre-merle** [comment]
LGTM :+1:

**Comment by LaurenSpiegel** [comment]
👍

**Pull request merged**
