### PR TITLE
ARSN-105 Disjointed reduced locations

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by jbertran** [comment]
Hello, I know Bert-E says `7.10.15`, but it's a bug - see https://scality.atlassian.net/browse/BERTE-564.

I recommend switching to `7.10.14` on the ticket and asking for a `bypass_jira_check` once you're satisfied with the PR, so that we're tracking the right things :)

**Comment by nicolas2bert** [comment]
@bert-e reset

**Review by miniscruff — APPROVED** [review]

**Review by naren-rajendran — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
