### PR TITLE
improvement: ARSN-225-add User Tag actionMaps

### PR DESCRIPTION
**Pull request by XinLi0207**
add new iam actions for User Tag feature
these actions are iam policy controlled.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM, maybe you also want to release Arsenal? In this case, you can bump the project version, and also deal with integration branches as these APIs will be also added to 8.x.

**Review by miniscruff — APPROVED** [review]

**Review by rachedbenmustapha — CHANGES_REQUESTED** [review]
According to [docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags_users.html) the case is wrong. Not that matching is case-sensitive (not sure about that), but the golden source should be properly written.

**Comment by XinLi0207** [comment]
@RachedBenMustapha thanks a lot for catching this!

**Review by rachedbenmustapha — APPROVED** [review]

**Pull request merged**
