### PR TITLE
Forward port from rel/7.1 to rel/7.2

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by nicolas2bert** [comment]
@ironman-machine try

**Comment by nicolas2bert** [comment]
@ironman-machine try

**Comment by nicolas2bert** [comment]
@ironman-machine clean

**Comment by nicolas2bert** [comment]
@ironman-machine try

**Comment by DavidPineauScality** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
Looks like we have to merge this using S3 forward port dependency branch.

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine 
CI_AGGRESSOR_FORCE_BUILD=1
try

**Comment by nicolas2bert** [comment]
@ironman-machine
DEFAULT_BRANCH=rel/7.2

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by ThibaultRiviere** [comment]
End to end retried and passed http://ci.ironmann.io/gh/scality/Integration/18040#build-parameters

**Pull request merged**
