### PR TITLE
ARSN-182 : Return error from callback intead of internal error

### PR DESCRIPTION
**Pull request by KillianG**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by jbertran** [comment]
Can we have a test for this, if only to have a guarantee of that contract in the tests?

**Comment by ghost** [comment]
Also nit: the ticket number in the commit is not the right one :slightly_smiling_face:

**Comment by KillianG** [comment]
> Can we have a test for this, if only to have a guarantee of that contract in the tests?

As mentionned in private on slack, this is already "tested" [here](https://github.com/scality/Arsenal/blob/0e3edb847ec1e8adff9a1eca79bbd9b61231db7d/tests/unit/storage/metadata/mongoclient/listObject.spec.js#L31)
Not totally tested but we cannot test deeper as this is in a pipe and I'm note able to mock it :/

**Review by ghost — APPROVED** [review]

**Review by XinLi0207 — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Pull request merged**
