### PR TITLE
Revert/7.2 get service cors [S3C-1009]

### PR DESCRIPTION
**Pull request by electrachong**
Dependency of https://github.com/scality/S3/pull/1036

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
@ironman-machine 
SCALITY_S3_BRANCH=revert/7.2-getService-cors
r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Comment by electrachong** [comment]
@ironman-machine r- r+

**Comment by dora-korpar** [comment]
@ironman-machine r- r+

**Comment by electrachong** [comment]
@ironman-machine 
try

**Comment by electrachong** [comment]
Manually merging; previous attempts failed due to flakiness.

**Pull request merged**
