### PR TITLE
bugfix: ZENKO-1195 Add keys and del Redis commands

### PR DESCRIPTION
**Pull request by bennettbuchanan**

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@bert-e

**Review by philipyoo — APPROVED** [review]

**Comment by bennettbuchanan** [comment]
@bert-e  wait

**Review by anurag4DSB — APPROVED** [review]

**Review by alexanderchan-scality — APPROVED** [review]

**Review by JianqinWang — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Comment by philipyoo** [comment]
I think the `keys` method is a blocking scan call and it's recommended to use `scan` instead if it is needed
https://stackoverflow.com/questions/32603964/scan-vs-keys-performance-in-redis

**Comment by bennettbuchanan** [comment]
Seeing as this is an edge case and we're already far along in the RC process for Zenko 1.1., I’m putting this on hold so that https://scality.atlassian.net/browse/ZENKOIO-11 can take precedence.

**Pull request closed without merging**
