### PR TITLE
ft: S3C-3040 add obj lock to iam policies

### PR DESCRIPTION
**Pull request by dora-korpar**
Adds Object Lock APIs to IAM Policy action list.

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Comment by dora-korpar** [comment]
@bert-e reset

**Comment by dora-korpar** [comment]
@bert-e approve

**Review by ilkescality — APPROVED** [review]

**Comment by dora-korpar** [comment]
@bert-e reset

**Review by ilkescality — CHANGES_REQUESTED** [review]
oh wait, just realized Put legal hold missing:)

**Review by ilkescality — APPROVED** [review]
sorry, just realized back that it was there _before_ :)

**Pull request merged**
