### PR TITLE
FIX: v4 signing tool

### PR DESCRIPTION
**Pull request by LaurenSpiegel**

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
@ironman-machine try

**Comment by LaurenSpiegel** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
I believe we encountered this with Utapi as well but I thought we had a fix for it. We may have fixed it in Utapi itself.

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Pull request merged**
