### PR TITLE
improvement:S3C-2352 switch package manager to yarn

### PR DESCRIPTION
**Pull request by Katherinelaue1**
**What does this PR do, and why do we need it?**
Switch testing framework to yarn

**Which issue does this PR fix?**
fixes #S3C-2352

**Special notes for your reviewers:**

### CODE REVIEW

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Comment by anurag4DSB** [comment]
In the dockerfile 
`RUN npm install mocha -g`
should be replaced by a yarn command.
refer to this: 

Probably something like:  RUN yarn global add mocha`

**Review by anurag4DSB — CHANGES_REQUESTED** [review]
In the dockerfile
`RUN npm install mocha -g`
should be replaced by a yarn command.
refer to this: https://yarnpkg.com/en/docs/migrating-from-npm#toc-cli-commands-comparison

Probably something like: `RUN yarn global add mocha`

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Review by JianqinWang — APPROVED** [review]
one comment - the testing framework is mocha, I believe we're switching out the package manager here :)

**Review by anurag4DSB — APPROVED** [review]

**Review by bennettbuchanan — APPROVED** [review]
Nice! :shipit:

**Review by JianqinWang — CHANGES_REQUESTED** [review]
Sorry for the block, but I believe `package-lock.json` files should be deleted from the 8.0/8.1 branches

**Review by jonathan-gramain — APPROVED** [review]

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Comment by Katherinelaue1** [comment]
@bert-e force_reset

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Review by JianqinWang — APPROVED** [review]

**Pull request merged**
