### PR TITLE
FT: Return logProxy from openRecordLog

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Needed for https://github.com/scality/backbeat/pull/37.

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
Seems like it timedout
@ironman-machine r-

**Comment by DavidPineauScality** [comment]
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
btrfs again
@ironman-machine r-

**Comment by DavidPineauScality** [comment]
@ironman-machine r+

**Comment by jonathan-gramain** [comment]
@ironman-machine try

**Pull request merged**
