### PR TITLE
Rename and Reorganise listing algorithms

### PR DESCRIPTION
**Pull request by DavidPineauScality**
The listing algorithms are currently exported "as is" from the index.js of Arsenal.

This PR provides a bit more logical isolation by providing a "list" object within an "algorithms" object to export. With this, it becomes clear what we are actually exporting, while lightening the actual names of the modules internally.

Following this, the files are moved/renamed for improved consistency and clarity.

Note that this PR should be merged after #97

### CODE REVIEW

**Comment by MathieuCassagne** [comment]
LGTM :+1:

**Comment by LaurenSpiegel** [comment]
👍

**Comment by rahulreddy** [comment]
#97 is going into rel/1.1, it should either go into master as this PR and the S3 PR are going into master as well or we should deal with fwdport stuff to get the changes into master

**Comment by DavidPineauScality** [comment]
I'll deal with the forward port between the two :)

**Comment by rahulreddy** [comment]
@DavidPineauScality Thanks!

**Comment by AntoninCoulibaly** [comment]
Sorry maybe a dumb question but for what purpose `sumSample.js` is there, it is not used or even exported ? For a future usage ? 
For the rest it seems good

**Comment by DavidPineauScality** [comment]
@AntoninCoulibaly I guess it was an artifact from the previous implementation and tests. I'll remove it :)

**Comment by AntoninCoulibaly** [comment]
Okok nice ;) :+1:

**Comment by DavidPineauScality** [comment]
Rebased, and re-fixed :) (so a few more files had to be moved around ^^)

**Comment by DavidPineauScality** [comment]
@rahulreddy looks like this one can be merged now, I just rebased it, and I got enough reviews on it.

**Comment by DavidPineauScality** [comment]
Merging on behalf of @rahulreddy, in order to sync-merge this PR and the two PRs in other repos relying on this one.

**Pull request merged**
