### PR TITLE
forward port of bf: sanity check on returned content-length

### PR DESCRIPTION
**Pull request by jonathan-gramain**
Additional fix on top of original PR:

Make sure contentLength is converted to a number because it might be a string.

This should fix failing tests.

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
@jonathan-gramain We need to merge the PR #365 and then forward port it. Otherwise we will be missing the merge commit from that PR.

**Comment by jonathan-gramain** [comment]
Will not forward-port, replaced by a normal PR on master https://github.com/scality/Arsenal/pull/365

**Pull request closed without merging**
