### PR TITLE
FIX: http/server: Fix error diplay (client error)

### PR DESCRIPTION
**Pull request by alexandre-merle**
Fix error display on client error in http server

### CODE REVIEW

**Comment by rahulreddy** [comment]
Can you re-target this to 6.3. We only push fixes to 6.2.5 if needed.

**Comment by alexandre-merle** [comment]
@rahulreddy rebased :)

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
End to end passed here http://ci.ironmann.io/gh/scality/Integration/9580#build-parameters

**Pull request merged**
