### PR TITLE
FIX: Case insensitive action

### PR DESCRIPTION
**Pull request by alexandre-merle**
Check with case insensitive the policy action

Fixes https://github.com/scality/Arsenal/issues/219

### CODE REVIEW

**Comment by alexandre-merle** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
Has this behavior been tested against AWS IAM?

**Comment by rahulreddy** [comment]
>You specify a value using a namespace that identifies a service (iam, ec2 sqs, sns, s3, etc.) followed by the name of the action to allow or deny. The name must match an action that is supported by the service. The prefix and the action name are case insensitive. For example, iam:ListAccessKeys is the same as IAM:listaccesskeys. The following examples show Action elements for different services.

Nevermind, I see it in the docs http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Action

**Comment by alexandre-merle** [comment]
@rahulreddy yes, i saw that in the doc too, that's why i made the pull request :)

**Comment by alexandre-merle** [comment]
@ironman-machine try

**Comment by alexandre-merle** [comment]
End to end here http://ci.ironmann.io/gh/scality/Integration/9605

**Comment by DavidPineauScality** [comment]
Merging on behalf of the maintainer

**Pull request merged**
