### PR TITLE
FWD: EVE Pipeline on 7.2

### PR DESCRIPTION
**Pull request by tcarmet**

### CODE REVIEW

**Comment by tcarmet** [comment]
@DavidPineauScality pensieve is not used on this version so I didn't add it

**Comment by DavidPineauScality** [comment]
Oh right, only on 7.4 then ?

**Comment by tcarmet** [comment]
Exactly. 7.4 and master

**Comment by DavidPineauScality** [comment]
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
@ironman-machine r- r+

**Comment by ThibaultRiviere** [comment]
Retried here: http://ci.ironmann.io/gh/scality/Integration/19346#build-parameters

**Comment by ThibaultRiviere** [comment]
Canceling the manually retry

**Comment by DavidPineauScality** [comment]
@ironman-machine r- r+

**Comment by DavidPineauScality** [comment]
@ironman-machine r- r+

**Comment by tcarmet** [comment]
Am I missing something ? This PR can be merged?

**Comment by ThibaultRiviere** [comment]
@tcarmet No no, the problem come from our end to end 
they are totally flacky

**Comment by ThibaultRiviere** [comment]
Merging manually since it doesn't touch the base code !

**Comment by tcarmet** [comment]
ok thanks @ThibaultRiviere 

I'll create the 7.4

**Pull request merged**
