### PR TITLE
FIX: http server + typo

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine

**Comment by rahulreddy** [comment]
@ironman-machine

**Comment by nicolas2bert** [comment]
http://ci.ironmann.io/gh/scality/Integration/13780

**Comment by rahulreddy** [comment]
@ironman-machine

**Comment by nicolas2bert** [comment]
Rebuilt without cache: http://ci.ironmann.io/gh/scality/Integration/13811

**Comment by LaurenSpiegel** [comment]
rebuild triggered by ci: http://ci.ironmann.io/gh/scality/Integration/13817

**Comment by LaurenSpiegel** [comment]
CI passed!!

**Pull request merged**
