### PR TITLE
refactor(werelogs): use new API

### PR DESCRIPTION
**Pull request by michael-zapata**
http://ci.ironmann.io/gh/scality/Integration/2367#build-parameters End to end passed without any problem.

### CODE REVIEW

**Comment by AntoninCoulibaly** [comment]
:+1:

**Comment by alexandre-merle** [comment]
:+1:

**Comment by MathieuCassagne** [comment]
:+1:

**Comment by michael-zapata** [comment]
Merging on behalf of @rahulreddy to get things going forward.

**Pull request merged**
