### PR TITLE
Fix: Wrap Azure calls with try/catch

### PR DESCRIPTION
**Pull request by dora-korpar**
Fix to handle when Azure requests throw errors instead of returning them in the callback.

Dependency of https://github.com/scality/S3/pull/934

### CODE REVIEW

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by LaurenSpiegel** [comment]
@ironman-machine r+

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by dora-korpar** [comment]
@ironman-machine r+

**Pull request merged**
